class CfgVehicles
{
	class TIOW_Fire_Warrior;
    class TIOW_FireWarrior_Base_TA_O: TIOW_Fire_Warrior
	{
		scope=1;
		side=0;
		icon="iconMan";
		picture="";
		identityTypes[]=
		{
			"Tau",
			"LanguageCHI_F"
		};
		faction="Tau_O";
		editorSubcategory="TA_Sept";
		uniformClass="TIOW_U_Fire_Warrior_TA_O";
		backpack="TIOW_Tau_Bck_Strike";
		weapons[]=
		{
			"TIOW_pulse_rifle",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt",
			"TIOW_Tau_HelmetS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt",
			"TIOW_Tau_HelmetS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle",
			"Throw",
			"Put"
		};
	};
    class TIOW_Strike_TA_Lead_O: TIOW_FireWarrior_Base_TA_O
	{
		scope=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui";
		weapons[]=
		{
			"TIOW_pulse_rifle",
			"TIOW_pulse_pistol",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui",
			"TIOW_Tau_HelmetS_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui",
			"TIOW_Tau_HelmetS_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle",
			"TIOW_pulse_pistol",
			"Throw",
			"Put"
		};
	};

	class TIOW_FireWarrior_Base_TA_B;
    class TIOW_Strike_TA_Lead_B: TIOW_FireWarrior_Base_TA_B
	{
		scope=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui";
		weapons[]=
		{
			"TIOW_pulse_rifle",
			"TIOW_pulse_pistol",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui",
			"TIOW_Tau_HelmetS_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui",
			"TIOW_Tau_HelmetS_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle",
			"TIOW_pulse_pistol",
			"Throw",
			"Put"
		};
	};

	class TIOW_FireWarrior_Base_TA_I;
    class TIOW_Strike_TA_Lead_I: TIOW_FireWarrior_Base_TA_I
	{
		scope=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui";
		weapons[]=
		{
			"TIOW_pulse_rifle",
			"TIOW_pulse_pistol",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui",
			"TIOW_Tau_HelmetS_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui",
			"TIOW_Tau_HelmetS_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle",
			"TIOW_pulse_pistol",
			"Throw",
			"Put"
		};
	};

	class TIOW_Fire_Warrior_DY;
    class TIOW_FireWarrior_Base_DY_O: TIOW_Fire_Warrior_DY
	{
		scope=1;
		scopeCurator=1;
		scopeArsenal=1;
		side=0;
		icon="iconMan";
		picture="";
		identityTypes[]=
		{
			"Tau",
			"LanguageCHI_F"
		};
		faction="Tau_O";
		editorSubcategory="DY_Sept";
		uniformClass="TIOW_U_Pathfinder_DY_O";
		backpack="TIOW_Tau_Bck_Strike_DY";
		weapons[]=
		{
			"TIOW_pulse_rifle_DY",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_DY",
			"TIOW_Tau_HelmetS_DY",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_DY",
			"TIOW_Tau_HelmetS_DY",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_DY",
			"Throw",
			"Put"
		};
	};
    class TIOW_Strike_DY_Lead_O: TIOW_FireWarrior_Base_DY_O
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_DY";
		weapons[]=
		{
			"TIOW_pulse_rifle_DY",
			"TIOW_pulse_pistol_DY",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_DY",
			"TIOW_Tau_HelmetS_DY_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_DY",
			"TIOW_Tau_HelmetS_DY_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_DY",
			"TIOW_pulse_pistol_DY",
			"Throw",
			"Put"
		};
	};
	
	class TIOW_FireWarrior_Base_DY_B;
    class TIOW_Strike_DY_Lead_B: TIOW_FireWarrior_Base_DY_B
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_DY";
		weapons[]=
		{
			"TIOW_pulse_rifle_DY",
			"TIOW_pulse_pistol_DY",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_DY",
			"TIOW_Tau_HelmetS_DY_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_DY",
			"TIOW_Tau_HelmetS_DY_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_DY",
			"TIOW_pulse_pistol_DY",
			"Throw",
			"Put"
		};
	};

	class TIOW_FireWarrior_Base_DY_I;
    class TIOW_Strike_DY_Lead_I: TIOW_FireWarrior_Base_DY_I
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_DY";
		weapons[]=
		{
			"TIOW_pulse_rifle_DY",
			"TIOW_pulse_pistol_DY",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_DY",
			"TIOW_Tau_HelmetS_DY_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_DY",
			"TIOW_Tau_HelmetS_DY_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_DY",
			"TIOW_pulse_pistol_DY",
			"Throw",
			"Put"
		};
	};

	class TIOW_Fire_Warrior_FE;
    class TIOW_FireWarrior_Base_FE_O: TIOW_Fire_Warrior_FE
	{
		scope=1;
		scopeCurator=1;
		scopeArsenal=1;
		side=0;
		icon="iconMan";
		picture="";
		identityTypes[]=
		{
			"Tau",
			"LanguageCHI_F"
		};
		faction="Tau_O";
		editorSubcategory="FE_Sept";
		uniformClass="TIOW_U_Pathfinder_FE_O";
		backpack="TIOW_Tau_Bck_Strike_FE";
		weapons[]=
		{
			"TIOW_pulse_rifle_FE",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_FE",
			"TIOW_Tau_HelmetS_FE",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_FE",
			"TIOW_Tau_HelmetS_FE",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_FE",
			"Throw",
			"Put"
		};
	};
    class TIOW_Strike_FE_Lead_O: TIOW_FireWarrior_Base_FE_O
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_FE";
		weapons[]=
		{
			"TIOW_pulse_rifle_FE",
			"TIOW_pulse_pistol_FE",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_FE",
			"TIOW_Tau_HelmetS_FE_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_FE",
			"TIOW_Tau_HelmetS_FE_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_FE",
			"TIOW_pulse_pistol_FE",
			"Throw",
			"Put"
		};
	};

	class TIOW_FireWarrior_Base_FE_B;
    class TIOW_Strike_FE_Lead_B: TIOW_FireWarrior_Base_FE_B
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_FE";
		weapons[]=
		{
			"TIOW_pulse_rifle_FE",
			"TIOW_pulse_pistol_FE",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_FE",
			"TIOW_Tau_HelmetS_FE_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_FE",
			"TIOW_Tau_HelmetS_FE_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_FE",
			"TIOW_pulse_pistol_FE",
			"Throw",
			"Put"
		};
	};

	class TIOW_FireWarrior_Base_FE_I;
    class TIOW_Strike_FE_Lead_I: TIOW_FireWarrior_Base_FE_I
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_FE";
		weapons[]=
		{
			"TIOW_pulse_rifle_FE",
			"TIOW_pulse_pistol_FE",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_FE",
			"TIOW_Tau_HelmetS_FE_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_FE",
			"TIOW_Tau_HelmetS_FE_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_FE",
			"TIOW_pulse_pistol_FE",
			"Throw",
			"Put"
		};
	};

	class TIOW_Fire_Warrior_SC;
    class TIOW_FireWarrior_Base_SC_O: TIOW_Fire_Warrior_SC
	{
		scope=1;
		scopeCurator=1;
		scopeArsenal=1;
		side=0;
		icon="iconMan";
		picture="";
		identityTypes[]=
		{
			"Tau",
			"LanguageCHI_F"
		};
		faction="Tau_O";
		editorSubcategory="SC_Sept";
		uniformClass="TIOW_U_Pathfinder_SC_O";
		backpack="TIOW_Tau_Bck_Strike_SC";
		weapons[]=
		{
			"TIOW_pulse_rifle_SC",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_SC",
			"TIOW_Tau_HelmetS_SC",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_SC",
			"TIOW_Tau_HelmetS_SC",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_SC",
			"Throw",
			"Put"
		};
	};
    class TIOW_Strike_SC_Lead_O: TIOW_FireWarrior_Base_SC_O
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_SC";
		weapons[]=
		{
			"TIOW_pulse_rifle_SC",
			"TIOW_pulse_pistol_SC",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_SC",
			"TIOW_Tau_HelmetS_SC_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_SC",
			"TIOW_Tau_HelmetS_SC_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_SC",
			"TIOW_pulse_pistol_SC",
			"Throw",
			"Put"
		};
	};

	class TIOW_FireWarrior_Base_SC_B;
    class TIOW_Strike_SC_Lead_B: TIOW_FireWarrior_Base_SC_B
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_SC";
		weapons[]=
		{
			"TIOW_pulse_rifle_SC",
			"TIOW_pulse_pistol_SC",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_SC",
			"TIOW_Tau_HelmetS_SC_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_SC",
			"TIOW_Tau_HelmetS_SC_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_SC",
			"TIOW_pulse_pistol_SC",
			"Throw",
			"Put"
		};
	};

	class TIOW_FireWarrior_Base_SC_I;
    class TIOW_Strike_SC_Lead_I: TIOW_FireWarrior_Base_SC_I
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_SC";
		weapons[]=
		{
			"TIOW_pulse_rifle_SC",
			"TIOW_pulse_pistol_SC",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_SC",
			"TIOW_Tau_HelmetS_SC_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_SC",
			"TIOW_Tau_HelmetS_SC_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_SC",
			"TIOW_pulse_pistol_SC",
			"Throw",
			"Put"
		};
	};

	class TIOW_Fire_Warrior_VL;
    class TIOW_FireWarrior_Base_VL_O: TIOW_Fire_Warrior_VL
	{
		scope=1;
		scopeCurator=1;
		scopeArsenal=1;
		side=0;
		icon="iconMan";
		picture="";
		identityTypes[]=
		{
			"Tau",
			"LanguageCHI_F"
		};
		faction="Tau_O";
		editorSubcategory="VL_Sept";
		uniformClass="TIOW_U_Pathfinder_VL_O";
		backpack="TIOW_Tau_Bck_Strike_VL";
		weapons[]=
		{
			"TIOW_pulse_rifle_VL",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_VL",
			"TIOW_Tau_HelmetS_VL",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_VL",
			"TIOW_Tau_HelmetS_VL",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_VL",
			"Throw",
			"Put"
		};
	};
    class TIOW_Strike_VL_Lead_O: TIOW_FireWarrior_Base_VL_O
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_VL";
		weapons[]=
		{
			"TIOW_pulse_rifle_VL",
			"TIOW_pulse_pistol_VL",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_VL",
			"TIOW_Tau_HelmetS_VL_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_VL",
			"TIOW_Tau_HelmetS_VL_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_VL",
			"TIOW_pulse_pistol_VL",
			"Throw",
			"Put"
		};
	};

	class TIOW_FireWarrior_Base_VL_B;
    class TIOW_Strike_VL_Lead_B: TIOW_FireWarrior_Base_VL_B
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_VL";
		weapons[]=
		{
			"TIOW_pulse_rifle_VL",
			"TIOW_pulse_pistol_VL",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_VL",
			"TIOW_Tau_HelmetS_VL_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_VL",
			"TIOW_Tau_HelmetS_VL_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_VL",
			"TIOW_pulse_pistol_VL",
			"Throw",
			"Put"
		};
	};

	class TIOW_FireWarrior_Base_VL_I;
    class TIOW_Strike_VL_Lead_I: TIOW_FireWarrior_Base_VL_I
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="Tau Fire Warrior Shasui";
		icon="iconManLeader";
		backpack="TIOW_Tau_Bck_Strike_Shasui_VL";
		weapons[]=
		{
			"TIOW_pulse_rifle_VL",
			"TIOW_pulse_pistol_VL",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		linkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_VL",
			"TIOW_Tau_HelmetS_VL_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Tau_Belt_Shasui_VL",
			"TIOW_Tau_HelmetS_VL_sui",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnMagazines[]=
		{
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"VNG_pulse_rifle_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_pulse_pistol_mag",
			"TIOW_tau_photon_grenade_mag",
			"TIOW_tau_photon_grenade_mag",
			"SmokeShellYellow",
			"SmokeShellYellow"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle_VL",
			"TIOW_pulse_pistol_VL",
			"Throw",
			"Put"
		};
	};
};