class CfgPatches {
	class VNG_TIOW_ADDON {
		author = "Onkel Dolf";
		name = "Vanguard TIOW Addon";
		requiredAddons[] = {"A3_Characters_F", "A3_Weapons_F", /*"TIOWSpaceMarines",*/ "CadFoot", "TIOW_AutoWeapons", "Cadian_Weapons", "DKoK_Weapons", "A40k_WepBase", "TIOW_Comissar", "TIOW_Mordians", "TIOW_Tau_FireWarior_Uniforms", "TIOW_Valhallans", "TIOW_Tau_Pathfinder_Uniforms", "TIOW_IG_Cosmetics", "TIOW_Spec_Weps", "ace_common", "TIOW_tau_40k_weapons", "ace_medical_treatment", "ace_trenches", "ace_parachute", "ace_flashlights", "ace_hearing"};
		requiredVersion = 0.1;
		units[] = {"VNG_CadATBackpack", "VNG_Vanguard_Vox_Operator", "VNG_Vanguard_Medicae", "VNG_Vanguard_Lieutenant", "VNG_Vanguard_AT_Rifleman", "VNG_Vanguard_Captain", "VNG_Vanguard_Flamer", "VNG_Vanguard_Grenadier", "VNG_Vanguard_Rifleman", "VNG_Vanguard_Meltagunner", "VNG_Vanguard_Ammo_Carrier_AT", "VNG_Vanguard_Sniper", "VNG_Vanguard_Plasmagunner"/*, "VNG_Vanguard_Chimera_w_Autocannon", "VNG_Vanguard_Centaur", "VNG_Vanguard_Taurox_w_Autocannon", "VNG_Vanguard_Taurox_w_Heavy_Stubber", "VNG_Vanguard_Trojan", "VNG_Vanguard_Leman_Russ_Annihilator","VNG_Vanguard_Leman_Russ_Battlecannon","VNG_Vanguard_Leman_Russ_Conqueror","VNG_Vanguard_Leman_Russ_Demolisher","VNG_Vanguard_Leman_Russ_Executioner","VNG_Vanguard_Leman_Russ_Punisher","VNG_Vanguard_Leman_Russ_Vanquisher","VNG_Vanguard_AA_Missile_Launcher_Emplacement","VNG_Vanguard_AT_Missile_Launcher_Emplacement","VNG_Vanguard_Autocannon_Emplacement","VNG_Vanguard_Heavy_Bolter_Emplacement","VNG_Vanguard_Lascannon_Emplacement","VNG_Vanguard_Mortar_Emplacement"*/};
		weapons[] = {"VNG_Gear", "VNG_MedGear", "VNG_Inf_Helm", "VNG_InfBreather_Helm", "VNG_LasLMGBase", "VNG_LasLMG", "VNG_Captain_Armor", "VNG_Commissar_Armor", "VNG_Krieg_Armor", "VNG_IG_GL", "VNG_MeltaGun", "VNG_KriegLauncher", "TIOW_Mk7PowerArmor_Tactical_2-1_Ravenspire"};
		magazines[]= {"VNG_HighPoweredM36KantRifle_mag", "VNG_150RndLasLmg_mag", "VNG_200RndLasLmg_mag", "VNG_75RndHighPoweredLasLmg_mag", "VNG_100RndHighPoweredLasLmg_mag", "VNG_100Rnd_Stubber_mag", "VNG_100Rnd_Stubber_mag_Tracer", "VNG_100Rnd_Stubber_amput", "VNG_100Rnd_Stubber_manstop", "VNG_100Rnd_Stubber_expander", "VNG_150Rnd_Stubber_mag", "VNG_150Rnd_Stubber_mag_Tracer", "VNG_150Rnd_Stubber_amput", "VNG_150Rnd_Stubber_manstop", "VNG_150Rnd_Stubber_expander", "VNG_MLSmoke_Mag", "VNG_MLMelta_Mag", "VNG_ionrifle_at_mag"};
		ammo[]= {"VNG_MLSmoke", "VNG_MLMelta", "VNG_HighDensityM36KantRifle_LasBolt", "VNG_ionrifle_at"};
		worlds[] = {};
	};
};