// Generated by unRap v1.06 by Kegetys
#include "script_macros_config.hpp"

class CfgVehicles {

    //////////////////////////////////////////////////////////////////////////////////////
	//TODO: Balance out the space marines so a Lucius pattern lasgun can't one shot them//
	//////////////////////////////////////////////////////////////////////////////////////

	
    class ThingX;	// External class reference
	class CAManBase;	// External class reference
	
	class SoldierWB : CAManBase {
		class HeadLimits;	// External class reference
	};
	
	class TIOWSpaceMarine_Base : SoldierWB {
		class HitPoints 
		{ // Additional info can be found on the wiki https://community.bistudio.com/wiki/Arma_3_Soldier_Protection
			 class HitFace
			 {
				armor = 9;  // "Healthpoints" of this hitpoint is armor value (of hitpoint) * armor value ( coefficient of the total armor defined below for the whole object
				material = -1; // damage material (-1 means "unused")
				name = "face_hub"; // selection name from hit points LOD in object
				passThrough = 0.8; // coefficient defining how much damage will pass into total damage when this hit point is damaged
				pen = 0.4; //Mod exclusive caculation
				radius = 0.08;// size of the hit point sphere, this is how it works: https://community.bistudio.com/wiki/Arma_3_Damage_Description
				explosionShielding = 0.1; // multiplier of explosive damage (parameter: explosive > 0 in ammunition type)
				minimalHit = 0.01; // minimal damage value that can be applied (based on armor value), damage below this threshold is ignored
			};
			class HitNeck: HitFace
			{
				armor = 40;
				material = -1;
				name = "neck";
				passThrough = 0.8;
				pen = 0.4;
				radius = 0.1;
				explosionShielding = 0.5;
				minimalHit = 0.01;
			};
			class HitHead: HitNeck
			{
				armor = 9;
				material = -1;
				name = "head";
				passThrough = 0.8;
				pen = 0.4;
				radius = 0.2;
				explosionShielding = 0.5;
				minimalHit = 0.01;
				depends = "HitFace max HitNeck";
			};
			class HitPelvis: HitHead
			{
				armor = 40;
				material = -1;
				name = "pelvis";
				passThrough = 0.8;
				pen = 0.4;
				radius = 0.24;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitAbdomen: HitPelvis
			{
				armor = 40;
				material = -1;
				name = "spine1";
				passThrough = 0.8;
				pen = 0.4;
				radius = 0.16;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitDiaphragm: HitAbdomen
			{
				armor = 40;
				material = -1;
				name = "spine2";
				passThrough = 0.8;
				pen = 0.4;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitChest: HitDiaphragm
			{
				armor = 40;
				material = -1;
				name = "spine3";
				passThrough = 0.8;
				pen = 0.4;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitBody: HitChest
			{
				armor = 1000;
				material = -1;
				name = "body";
				passThrough = 1;
				pen = 0.4;
				radius = 0;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "HitPelvis max HitAbdomen max HitDiaphragm max HitChest";
			};
			class HitArms: HitBody
			{
				armor = 40;
				material = -1;
				name = "arms";
				passThrough = 1;
				pen = 0.4;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitHands: HitArms
			{
				armor = 40;
				material = -1;
				name = "hands";
				passThrough = 1;
				pen = 0.4;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "HitArms";
			};
			class HitLegs: HitHands
			{
				armor = 40;
				material = -1;
				name = "legs";
				passThrough = 1;
				pen = 0.4;
				radius = 0.14;
				explosionShielding = 1;
				visual = "injury_legs";
				minimalHit = 0.01;
				depends = "0";
			};
			class Incapacitated: HitLegs
			{
				armor = 1000;
				material = -1;
				name = "body";
				passThrough = 1;
				pen = 0.4;
				radius = 0;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "(((Total - 0.25) max 0) + ((HitHead - 0.25) max 0) + ((HitBody - 0.25) max 0)) * 2";
			};
			class HitLeftArm
			{
				armor = 40;
				material = -1;
				name = "hand_l";
				passThrough = 1;
				pen = 0.4;
				radius = 0.08;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
			};
			class HitRightArm: HitLeftArm
			{
				name = "hand_r";
			};
			class HitLeftLeg
			{
				armor = 40;
				material = -1;
				name = "leg_l";
				passThrough = 1;
				pen = 0.4;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_legs";
				minimalHit = 0.01;
			};
			class HitRightLeg: HitLeftLeg
			{
				name = "leg_r";
			};
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			}
		};
		armor = 40;
		armorStructural = 10.0;
		explosionShielding = 10.25;
		class EventHandlers;	// External class reference
		weapons[] = {"Throw", "Put"};
		respawnweapons[] = {"Throw", "Put"};
		Items[] = {};
		RespawnItems[] = {};
		magazines[] = {};
		respawnMagazines[] = {};
		linkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		uniformAccessories[] = {};
	};
    
    class B_Soldier_F;
	class Strategic;
	class ReammoBox: Strategic
	{
	};
	class Bag_Base: ReammoBox
	{
	};
	class B_AssaultPack_Base: Bag_Base
	{
	};
	class B_AssaultPack_rgr: B_AssaultPack_Base
	{
	};
    
    class TIOW_CadBackpack: B_AssaultPack_Base
	{
		author="1st Legion";
		scope=2;
		picture="\CadFoot\Icon\Backpack_ca.paa";
		displayName="[Cadian] Infantry Backpack";
		model="\CadFoot\Model\Backpack.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\Backpack_co.paa"
		};
		class TransportMagazines
		{
			class _xx_M36KantRifle_mag
			{
				magazine="M36KantRifle_mag";
				count=6;
			};
			class _xx_HandGrenade
			{
				magazine="HandGrenade";
				count=4;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=2;
			};
		};
	};
    class TIOW_CadMedicaeBackpack: B_AssaultPack_Base
	{
		author="1st Legion";
		scope=2;
        maximumLoad = 240;
		picture="\CadFoot\Icon\Backpack_ca.paa";
		displayName="[Cadian] Medicae Backpack";
		model="\CadFoot\Model\Backpack.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\MedicaeBackpack_co.paa"
		};
		class TransportMagazines
		{
			class _xx_M36KantRifle_mag
			{
				magazine="M36KantRifle_mag";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=2;
			};
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
		};
	};

	class TIOW_CadMedicaeBackpack_Winter: B_AssaultPack_Base
	{
		author="1st Legion";
		scope=2;
        maximumLoad = 240;
		picture="\CadFoot\Icon\Backpack_ca.paa";
		displayName="[Cadian] Medicae Backpack (Winter Camo)";
		model="\CadFoot\Model\Backpack.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\MedicaeBackpackWinter_co.paa"
		};
		class TransportMagazines
		{
			class _xx_M36KantRifle_mag
			{
				magazine="M36KantRifle_mag";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=2;
			};
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
		};
	};

    class VNG_CadATBackpack: TIOW_CadBackpack
	{
		displayName="[Cadian] Infantry AT Backpack";
	    maximumLoad = 320;
	};

    class B_Soldier_base_F;

    class DKoK_GM_1: B_Soldier_F
	{
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		identityTypes[]=
		{
			"LanguageENGB_F",
			"Head_Dkok",
			"Male01DKoK"
		};
		faceType="Man_A3";
		genericNames="DKOKMen";
		displayName="Death Korps Guardsman";
		Faction="DKoK";
		vehicleClass="DKok_Inf";
		uniformAccessories[]={};
		nakedUniform="U_BasicBody";
		uniformClass="DKoK_GM_Uniform";
		model="DKoKFoot\Model\DKoK_Uniform.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camob"
		};
		class HitPoints
		{
			class HitFace
			{
				armor = 1;
				material = -1;
				name = "face_hub";
				passThrough = 0.8;
				radius = 0.08;
				explosionShielding = 0.1;
				minimalHit = 0.01;
			};
			class HitNeck: HitFace
			{
				armor = 1;
				material = -1;
				name = "neck";
				passThrough = 0.8;
				radius = 0.1;
				explosionShielding = 0.5;
				minimalHit = 0.01;
			};
			class HitHead: HitNeck
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0.8;
				radius = 0.2;
				explosionShielding = 0.5;
				minimalHit = 0.01;
				depends = "HitFace max HitNeck";
			};
			class HitPelvis: HitHead
			{
				armor = 6;
				material = -1;
				name = "pelvis";
				passThrough = 0.8;
				radius = 0.24;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitAbdomen: HitPelvis
			{
				armor = 1;
				material = -1;
				name = "spine1";
				passThrough = 0.8;
				radius = 0.16;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitDiaphragm: HitAbdomen
				{
				armor = 1;
				material = -1;
				name = "spine2";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitChest: HitDiaphragm
			{
				armor = 1;
				material = -1;
				name = "spine3";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitBody: HitChest
			{
				armor = 1000;
				material = -1;
				name = "body";
				passThrough = 1;
				radius = 0;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "HitPelvis max HitAbdomen max HitDiaphragm max HitChest";
			};
			class HitArms: HitBody
			{
				armor = 3;
				material = -1;
				name = "arms";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitHands: HitArms
			{
				armor = 3;
				material = -1;
				name = "hands";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "HitArms";
			};
			class HitLegs: HitHands
			{
				armor = 3;
				material = -1;
				name = "legs";
				passThrough = 1;
				radius = 0.14;
				explosionShielding = 1;
				visual = "injury_legs";
				minimalHit = 0.01;
				depends = "0";
			};
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			}
		};
		armor = 2;
		armorStructural = 3;
		explosionShielding = 0.3;
		hiddenSelectionsTextures[]={};
		linkedItems[]=
		{
			"DKOKTroopMask",
			"DKoK_GM_Helm",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"TIOW_Krieg_Armor"
		};
		RespawnLinkedItems[]=
		{
			"DKOKTroopMask",
			"DKoK_GM_Helm",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"TIOW_Krieg_Armor"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		backpack="DKoK_Backpack";
		magazines[]=
		{
			"Lucius98_mag",
			"Lucius98_mag",
			"Lucius98_mag",
			"Lucius98_mag",
			"HandGrenade",
			"HandGrenade"
		};
		respawnmagazines[]=
		{
			"Lucius98_mag",
			"Lucius98_mag",
			"Lucius98_mag",
			"Lucius98_mag",
			"HandGrenade",
			"HandGrenade"
		};
	};
    class TIOW_Comissar: B_Soldier_base_F
	{
		displayName="Commissar";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"Comissar",
			"LanguageENGB_F",
			"NoGlasses"
		};
		model="\TIOW_IG_HQ\Comissar\Comissar.p3d";
		uniformClass="U_TIOW_Comissar";
		nakedUniform="U_BasicBody";
		icon="iconManEngineer";
		picture="pictureRepair";
		glassesEnabled=1;
		camouflage=1;
		faction="TIOW_IG_HQ_B";
		backpack="";
		vest="";
		weapons[]=
		{
			"Throw",
			"Put",
			"TIOW_bolt_pistol"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"TIOW_bolt_pistol"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag"
		};
		respawnMagazines[]=
		{
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag"
		};
		linkedItems[]=
		{
			"TIOW_Bionic_Eye",
			"TIOW_Comissar_Cap",
			"TIOW_Commissar_Armor"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Bionic_Eye",
			"TIOW_Comissar_Cap",
			"TIOW_Commissar_Armor"
		};
		class HitPoints
		{
			class HitFace
			{
				armor = 1;
				material = -1;
				name = "face_hub";
				passThrough = 0.8;
				radius = 0.08;
				explosionShielding = 0.1;
				minimalHit = 0.01;
			};
			class HitNeck: HitFace
			{
				armor = 1;
				material = -1;
				name = "neck";
				passThrough = 0.8;
				radius = 0.1;
				explosionShielding = 0.5;
				minimalHit = 0.01;
			};
			class HitHead: HitNeck
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0.8;
				radius = 0.2;
				explosionShielding = 0.5;
				minimalHit = 0.01;
				depends = "HitFace max HitNeck";
			};
			class HitPelvis: HitHead
			{
				armor = 6;
				material = -1;
				name = "pelvis";
				passThrough = 0.8;
				radius = 0.24;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitAbdomen: HitPelvis
			{
				armor = 1;
				material = -1;
				name = "spine1";
				passThrough = 0.8;
				radius = 0.16;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitDiaphragm: HitAbdomen
				{
				armor = 1;
				material = -1;
				name = "spine2";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitChest: HitDiaphragm
			{
				armor = 1;
				material = -1;
				name = "spine3";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitBody: HitChest
			{
				armor = 1000;
				material = -1;
				name = "body";
				passThrough = 1;
				radius = 0;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "HitPelvis max HitAbdomen max HitDiaphragm max HitChest";
			};
			class HitArms: HitBody
			{
				armor = 3;
				material = -1;
				name = "arms";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitHands: HitArms
			{
				armor = 3;
				material = -1;
				name = "hands";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "HitArms";
			};
			class HitLegs: HitHands
			{
				armor = 3;
				material = -1;
				name = "legs";
				passThrough = 1;
				radius = 0.14;
				explosionShielding = 1;
				visual = "injury_legs";
				minimalHit = 0.01;
				depends = "0";
			};
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			}
		};
		armor = 2;
		armorStructural = 3;
		explosionShielding = 0.3;
		class UniformInfo
		{
			class SlotsInfo
			{
				class UniformSlotInfo;
				class NVG: UniformSlotInfo
				{
					slotType="NVG_SLOT";
				};
				class Scuba: UniformSlotInfo
				{
					slotType="SCUBA_SLOT";
				};
				class Googles: UniformSlotInfo
				{
					slotType="GOGGLE_SLOT";
				};
				class Headgear: UniformSlotInfo
				{
					slotType="HEADGEAR_SLOT";
				};
			};
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_HQ\Comissar\data\uniform_CA.paa",
			"\TIOW_IG_HQ\Comissar\data\coat_CA.paa"
		};
	};
    class TIOW_IG_Captain_667: B_Soldier_base_F
	{
		displayName="Captain (667th)";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"Captain",
			"LanguageENGB_F",
			"NoGlasses"
		};
		model="\TIOW_IG_HQ\Captain\IG_Captain.p3d";
		uniformClass="U_TIOW_Captain_667";
		nakedUniform="U_BasicBody";
		icon="iconManEngineer";
		picture="pictureRepair";
		glassesEnabled=1;
		camouflage=1;
		faction="TIOW_IG_HQ_B";
		backpack="";
		vest="";
		weapons[]=
		{
			"Throw",
			"Put",
			"TIOW_bolt_pistol"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"TIOW_bolt_pistol"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag"
		};
		respawnMagazines[]=
		{
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag"
		};
		linkedItems[]=
		{
			"TIOW_Bionic_Eye",
			"TIOW_Comissar_Cap",
			"TIOW_Captain_Armor"
		};
		respawnLinkedItems[]=
		{
			"TIOW_Bionic_Eye",
			"TIOW_Comissar_Cap",
			"TIOW_Captain_Armor"
		};
		class HitPoints
		{
			class HitFace
			{
				armor = 1;
				material = -1;
				name = "face_hub";
				passThrough = 0.8;
				radius = 0.08;
				explosionShielding = 0.1;
				minimalHit = 0.01;
			};
			class HitNeck: HitFace
			{
				armor = 1;
				material = -1;
				name = "neck";
				passThrough = 0.8;
				radius = 0.1;
				explosionShielding = 0.5;
				minimalHit = 0.01;
			};
			class HitHead: HitNeck
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0.8;
				radius = 0.2;
				explosionShielding = 0.5;
				minimalHit = 0.01;
				depends = "HitFace max HitNeck";
			};
			class HitPelvis: HitHead
			{
				armor = 6;
				material = -1;
				name = "pelvis";
				passThrough = 0.8;
				radius = 0.24;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitAbdomen: HitPelvis
			{
				armor = 1;
				material = -1;
				name = "spine1";
				passThrough = 0.8;
				radius = 0.16;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitDiaphragm: HitAbdomen
				{
				armor = 1;
				material = -1;
				name = "spine2";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitChest: HitDiaphragm
			{
				armor = 1;
				material = -1;
				name = "spine3";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitBody: HitChest
			{
				armor = 1000;
				material = -1;
				name = "body";
				passThrough = 1;
				radius = 0;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "HitPelvis max HitAbdomen max HitDiaphragm max HitChest";
			};
			class HitArms: HitBody
			{
				armor = 3;
				material = -1;
				name = "arms";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitHands: HitArms
			{
				armor = 3;
				material = -1;
				name = "hands";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "HitArms";
			};
			class HitLegs: HitHands
			{
				armor = 3;
				material = -1;
				name = "legs";
				passThrough = 1;
				radius = 0.14;
				explosionShielding = 1;
				visual = "injury_legs";
				minimalHit = 0.01;
				depends = "0";
			};
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			}
		};
		armor = 2;
		armorStructural = 3;
		explosionShielding = 0.3;
		class UniformInfo
		{
			class SlotsInfo
			{
				class UniformSlotInfo;
				class NVG: UniformSlotInfo
				{
					slotType="NVG_SLOT";
				};
				class Scuba: UniformSlotInfo
				{
					slotType="SCUBA_SLOT";
				};
				class Googles: UniformSlotInfo
				{
					slotType="GOGGLE_SLOT";
				};
				class Headgear: UniformSlotInfo
				{
					slotType="HEADGEAR_SLOT";
				};
			};
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_HQ\Captain\data\Cadian_officer_667_CA.paa",
			"\TIOW_IG_HQ\Captain\data\Cadian_officer_detail_667_CA.paa"
		};
	};
    class TIOW_Priest: B_Soldier_base_F
	{
		displayName="Priest";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"Priest",
			"LanguageENGB_F",
			"NoGlasses"
		};
		model="\TIOW_IG_HQ\Priest\Priest_robe.p3d";
		uniformClass="U_TIOW_Priest";
		nakedUniform="U_BasicBody";
		icon="iconManEngineer";
		picture="pictureRepair";
		glassesEnabled=1;
		camouflage=1;
		faction="TIOW_IG_HQ_B";
		backpack="";
		vest="";
		weapons[]=
		{
			"Throw",
			"Put",
			"TIOW_bolt_pistol"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"TIOW_bolt_pistol"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag"
		};
		respawnMagazines[]=
		{
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag",
			"TIOW_IGBoltPistol_Mag"
		};
		linkedItems[]=
		{
			"TIOW_Priest_Hood",
			"TIOW_Priest_Gear",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		RespawnLinkedItems[]=
		{
			"TIOW_Priest_Hood",
			"TIOW_Priest_Gear",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		class HitPoints
		{
			class HitFace
			{
				armor = 1;
				material = -1;
				name = "face_hub";
				passThrough = 0.8;
				radius = 0.08;
				explosionShielding = 0.1;
				minimalHit = 0.01;
			};
			class HitNeck: HitFace
			{
				armor = 1;
				material = -1;
				name = "neck";
				passThrough = 0.8;
				radius = 0.1;
				explosionShielding = 0.5;
				minimalHit = 0.01;
			};
			class HitHead: HitNeck
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0.8;
				radius = 0.2;
				explosionShielding = 0.5;
				minimalHit = 0.01;
				depends = "HitFace max HitNeck";
			};
			class HitPelvis: HitHead
			{
				armor = 6;
				material = -1;
				name = "pelvis";
				passThrough = 0.8;
				radius = 0.24;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitAbdomen: HitPelvis
			{
				armor = 1;
				material = -1;
				name = "spine1";
				passThrough = 0.8;
				radius = 0.16;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitDiaphragm: HitAbdomen
				{
				armor = 1;
				material = -1;
				name = "spine2";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitChest: HitDiaphragm
			{
				armor = 1;
				material = -1;
				name = "spine3";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitBody: HitChest
			{
				armor = 1000;
				material = -1;
				name = "body";
				passThrough = 1;
				radius = 0;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "HitPelvis max HitAbdomen max HitDiaphragm max HitChest";
			};
			class HitArms: HitBody
			{
				armor = 3;
				material = -1;
				name = "arms";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitHands: HitArms
			{
				armor = 3;
				material = -1;
				name = "hands";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "HitArms";
			};
			class HitLegs: HitHands
			{
				armor = 3;
				material = -1;
				name = "legs";
				passThrough = 1;
				radius = 0.14;
				explosionShielding = 1;
				visual = "injury_legs";
				minimalHit = 0.01;
				depends = "0";
			};
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			}
		};
		armor = 2;
		armorStructural = 3;
		explosionShielding = 0.3;
		class UniformInfo
		{
			class SlotsInfo
			{
				class UniformSlotInfo;
				class NVG: UniformSlotInfo
				{
					slotType="NVG_SLOT";
				};
				class Scuba: UniformSlotInfo
				{
					slotType="SCUBA_SLOT";
				};
				class Googles: UniformSlotInfo
				{
					slotType="GOGGLE_SLOT";
				};
				class Headgear: UniformSlotInfo
				{
					slotType="HEADGEAR_SLOT";
				};
			};
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_HQ\Priest\data\Priest_Robes_CA.paa"
		};
	};
    class TIOW_Mordian_Trooper_1_Blu: B_Soldier_base_F
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"Mordian",
			"LanguageENGB_F"
		};
		model="\TIOW_Mordian\TIOW_Mordian_Uniforms\Mordian_uniform.p3d";
		uniformClass="U_TIOW_Mordian_Blu";
		nakedUniform="U_BasicBody";
		glassesEnabled=0;
		camouflage=1;
		displayName="Mordian Trooper";
		editorSubcategory="EdSubcat_TIOW_Mordian";
		faction="TIOW_Mordian_Blu";
		backpack="";
		weapons[]=
		{
			"M36KantRifle776",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"M36KantRifle776",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"HandGrenade",
			"HandGrenade"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"TIOW_Mordian_Belt",
			"TIOW_Mordian_Cap_2"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"TIOW_Mordian_Belt",
			"TIOW_Mordian_Cap_2"
		};
		class HitPoints
		{
			class HitFace
			{
				armor = 1;
				material = -1;
				name = "face_hub";
				passThrough = 0.8;
				radius = 0.08;
				explosionShielding = 0.1;
				minimalHit = 0.01;
			};
			class HitNeck: HitFace
			{
				armor = 1;
				material = -1;
				name = "neck";
				passThrough = 0.8;
				radius = 0.1;
				explosionShielding = 0.5;
				minimalHit = 0.01;
			};
			class HitHead: HitNeck
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0.8;
				radius = 0.2;
				explosionShielding = 0.5;
				minimalHit = 0.01;
				depends = "HitFace max HitNeck";
			};
			class HitPelvis: HitHead
			{
				armor = 6;
				material = -1;
				name = "pelvis";
				passThrough = 0.8;
				radius = 0.24;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitAbdomen: HitPelvis
			{
				armor = 1;
				material = -1;
				name = "spine1";
				passThrough = 0.8;
				radius = 0.16;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitDiaphragm: HitAbdomen
				{
				armor = 1;
				material = -1;
				name = "spine2";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitChest: HitDiaphragm
			{
				armor = 1;
				material = -1;
				name = "spine3";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitBody: HitChest
			{
				armor = 1000;
				material = -1;
				name = "body";
				passThrough = 1;
				radius = 0;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "HitPelvis max HitAbdomen max HitDiaphragm max HitChest";
			};
			class HitArms: HitBody
			{
				armor = 3;
				material = -1;
				name = "arms";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitHands: HitArms
			{
				armor = 3;
				material = -1;
				name = "hands";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "HitArms";
			};
			class HitLegs: HitHands
			{
				armor = 3;
				material = -1;
				name = "legs";
				passThrough = 1;
				radius = 0.14;
				explosionShielding = 1;
				visual = "injury_legs";
				minimalHit = 0.01;
				depends = "0";
			};
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			}
		};
		armor = 2;
		armorStructural = 3;
		explosionShielding = 0.3;
		class UniformInfo
		{
			class SlotsInfo
			{
				class UniformSlotInfo;
				class NVG: UniformSlotInfo
				{
					slotType="NVG_SLOT";
				};
				class Scuba: UniformSlotInfo
				{
					slotType="SCUBA_SLOT";
				};
				class Googles: UniformSlotInfo
				{
					slotType="GOGGLE_SLOT";
				};
				class Headgear: UniformSlotInfo
				{
					slotType="HEADGEAR_SLOT";
				};
			};
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_Mordian\TIOW_Mordian_Uniforms\data\Mordian_top_CA.paa",
			"\TIOW_Mordian\TIOW_Mordian_Uniforms\data\Mordian_bottom_CA.paa"
		};
	};
    class TIOW_Fire_Warrior: B_Soldier_base_F
	{
		scope=1;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"Tau",
			"LanguageENGB_F"
		};
		model="\40k_tau\Fire_Warrior\Fire_Warrior.p3d";
		uniformClass="U_TIOW_Fire_Warrior";
		nakedUniform="U_BasicBody";
		icon="iconManEngineer";
		picture="pictureRepair";
		glassesEnabled=0;
		camouflage=1;
		backpack="TIOW_Tau_Bck_Strike";
		vest="TIOW_Tau_Belt";
		weapons[]=
		{
			"TIOW_pulse_rifle",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag"
		};
		respawnMagazines[]=
		{
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag"
		};
		linkedItems[]={};
		respawnLinkedItems[]={};
		class HitPoints
		{
			class HitFace
			{
				armor = 1;
				material = -1;
				name = "face_hub";
				passThrough = 0.8;
				radius = 0.08;
				explosionShielding = 0.1;
				minimalHit = 0.01;
			};
			class HitNeck: HitFace
			{
				armor = 1;
				material = -1;
				name = "neck";
				passThrough = 0.8;
				radius = 0.1;
				explosionShielding = 0.5;
				minimalHit = 0.01;
			};
			class HitHead: HitNeck
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0.8;
				radius = 0.2;
				explosionShielding = 0.5;
				minimalHit = 0.01;
				depends = "HitFace max HitNeck";
			};
			class HitPelvis: HitHead
			{
				armor = 6;
				material = -1;
				name = "pelvis";
				passThrough = 0.8;
				radius = 0.24;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitAbdomen: HitPelvis
			{
				armor = 1;
				material = -1;
				name = "spine1";
				passThrough = 0.8;
				radius = 0.16;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitDiaphragm: HitAbdomen
				{
				armor = 1;
				material = -1;
				name = "spine2";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitChest: HitDiaphragm
			{
				armor = 1;
				material = -1;
				name = "spine3";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitBody: HitChest
			{
				armor = 1000;
				material = -1;
				name = "body";
				passThrough = 1;
				radius = 0;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "HitPelvis max HitAbdomen max HitDiaphragm max HitChest";
			};
			class HitArms: HitBody
			{
				armor = 3;
				material = -1;
				name = "arms";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitHands: HitArms
			{
				armor = 3;
				material = -1;
				name = "hands";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "HitArms";
			};
			class HitLegs: HitHands
			{
				armor = 3;
				material = -1;
				name = "legs";
				passThrough = 1;
				radius = 0.14;
				explosionShielding = 1;
				visual = "injury_legs";
				minimalHit = 0.01;
				depends = "0";
			};
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			}
		};
		armor = 2;
		armorStructural = 3;
		explosionShielding = 0.3;
		class UniformInfo
		{
			class SlotsInfo
			{
				class UniformSlotInfo;
				class NVG: UniformSlotInfo
				{
					slotType="NVG_SLOT";
				};
				class Scuba: UniformSlotInfo
				{
					slotType="SCUBA_SLOT";
				};
				class Googles: UniformSlotInfo
				{
					slotType="GOGGLE_SLOT";
				};
				class Headgear: UniformSlotInfo
				{
					slotType="HEADGEAR_SLOT";
				};
			};
		};
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\40k_tau\Fire_Warrior\data\FW_Armour_CA",
			"\40k_tau\Fire_Warrior\data\FW_Cloth_CA"
		};
	};
	class TIOW_Valhallan_Trooper_1_Blu: B_Soldier_base_F
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"Valhallan",
			"LanguageENGB_F"
		};
		model="\TIOW_Valhallans\TIOW_Valhallan_Uniforms\Valhallan_uniform.p3d";
		uniformClass="U_TIOW_Valhallan_Blu";
		nakedUniform="U_BasicBody";
		glassesEnabled=0;
		camouflage=1;
		displayName="Valhallan Trooper";
		editorSubcategory="EdSubcat_TIOW_Val";
		faction="TIOW_Val_Blu";
		backpack="TIOW_Valhallan_Bandolier";
		weapons[]=
		{
			"M36KantRifle776",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"M36KantRifle776",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"M36KantRifle_mag",
			"HandGrenade",
			"HandGrenade"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"TIOW_Valhallan_Belt",
			"TIOW_Valhallan_Cap_2"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"TIOW_Valhallan_Belt",
			"TIOW_Valhallan_Cap_2"
		};
		class UniformInfo
		{
			class SlotsInfo
			{
				class UniformSlotInfo;
				class NVG: UniformSlotInfo
				{
					slotType="NVG_SLOT";
				};
				class Scuba: UniformSlotInfo
				{
					slotType="SCUBA_SLOT";
				};
				class Googles: UniformSlotInfo
				{
					slotType="GOGGLE_SLOT";
				};
				class Headgear: UniformSlotInfo
				{
					slotType="HEADGEAR_SLOT";
				};
			};
		};
		class HitPoints
		{
			class HitFace
			{
				armor = 1;
				material = -1;
				name = "face_hub";
				passThrough = 0.8;
				radius = 0.08;
				explosionShielding = 0.1;
				minimalHit = 0.01;
			};
			class HitNeck: HitFace
			{
				armor = 1;
				material = -1;
				name = "neck";
				passThrough = 0.8;
				radius = 0.1;
				explosionShielding = 0.5;
				minimalHit = 0.01;
			};
			class HitHead: HitNeck
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0.8;
				radius = 0.2;
				explosionShielding = 0.5;
				minimalHit = 0.01;
				depends = "HitFace max HitNeck";
			};
			class HitPelvis: HitHead
			{
				armor = 6;
				material = -1;
				name = "pelvis";
				passThrough = 0.8;
				radius = 0.24;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitAbdomen: HitPelvis
			{
				armor = 1;
				material = -1;
				name = "spine1";
				passThrough = 0.8;
				radius = 0.16;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitDiaphragm: HitAbdomen
				{
				armor = 1;
				material = -1;
				name = "spine2";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitChest: HitDiaphragm
			{
				armor = 1;
				material = -1;
				name = "spine3";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitBody: HitChest
			{
				armor = 1000;
				material = -1;
				name = "body";
				passThrough = 1;
				radius = 0;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "HitPelvis max HitAbdomen max HitDiaphragm max HitChest";
			};
			class HitArms: HitBody
			{
				armor = 3;
				material = -1;
				name = "arms";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitHands: HitArms
			{
				armor = 3;
				material = -1;
				name = "hands";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "HitArms";
			};
			class HitLegs: HitHands
			{
				armor = 3;
				material = -1;
				name = "legs";
				passThrough = 1;
				radius = 0.14;
				explosionShielding = 1;
				visual = "injury_legs";
				minimalHit = 0.01;
				depends = "0";
			};
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			}
		};
		armor = 2;
		armorStructural = 3;
		explosionShielding = 0.3;
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_Valhallans\TIOW_Valhallan_Uniforms\data\uniform_CA.paa",
			"\TIOW_Valhallans\TIOW_Valhallan_Uniforms\data\mittens_black_CA.paa"
		};
	};
	class TIOW_Pathfinder: B_Soldier_base_F
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"Tau"
		};
		model="\40k_tau\Pathfinder\Pathfinder.p3d";
		uniformClass="U_TIOW_Pathfinder";
		nakedUniform="U_BasicBody";
		icon="iconManEngineer";
		picture="pictureRepair";
		glassesEnabled=0;
		camouflage=1;
		backpack="TIOW_Tau_Bck_Strike";
		vest="TIOW_Tau_Belt";
		weapons[]=
		{
			"TIOW_pulse_rifle",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"TIOW_pulse_rifle",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		magazines[]=
		{
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag"
		};
		respawnMagazines[]=
		{
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag",
			"TIOW_pulse_mag"
		};
		linkedItems[]={};
		respawnLinkedItems[]={};
		class UniformInfo
		{
			class SlotsInfo
			{
				class UniformSlotInfo;
				class NVG: UniformSlotInfo
				{
					slotType="NVG_SLOT";
				};
				class Scuba: UniformSlotInfo
				{
					slotType="SCUBA_SLOT";
				};
				class Googles: UniformSlotInfo
				{
					slotType="GOGGLE_SLOT";
				};
				class Headgear: UniformSlotInfo
				{
					slotType="HEADGEAR_SLOT";
				};
			};
		};
		class HitPoints
		{
			class HitFace
			{
				armor = 1;
				material = -1;
				name = "face_hub";
				passThrough = 0.8;
				radius = 0.08;
				explosionShielding = 0.1;
				minimalHit = 0.01;
			};
			class HitNeck: HitFace
			{
				armor = 1;
				material = -1;
				name = "neck";
				passThrough = 0.8;
				radius = 0.1;
				explosionShielding = 0.5;
				minimalHit = 0.01;
			};
			class HitHead: HitNeck
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0.8;
				radius = 0.2;
				explosionShielding = 0.5;
				minimalHit = 0.01;
				depends = "HitFace max HitNeck";
			};
			class HitPelvis: HitHead
			{
				armor = 6;
				material = -1;
				name = "pelvis";
				passThrough = 0.8;
				radius = 0.24;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitAbdomen: HitPelvis
			{
				armor = 1;
				material = -1;
				name = "spine1";
				passThrough = 0.8;
				radius = 0.16;
				explosionShielding = 1;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitDiaphragm: HitAbdomen
				{
				armor = 1;
				material = -1;
				name = "spine2";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitChest: HitDiaphragm
			{
				armor = 1;
				material = -1;
				name = "spine3";
				passThrough = 0.8;
				radius = 0.18;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
			};
			class HitBody: HitChest
			{
				armor = 1000;
				material = -1;
				name = "body";
				passThrough = 1;
				radius = 0;
				explosionShielding = 6;
				visual = "injury_body";
				minimalHit = 0.01;
				depends = "HitPelvis max HitAbdomen max HitDiaphragm max HitChest";
			};
			class HitArms: HitBody
			{
				armor = 3;
				material = -1;
				name = "arms";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "0";
			};
			class HitHands: HitArms
			{
				armor = 3;
				material = -1;
				name = "hands";
				passThrough = 1;
				radius = 0.1;
				explosionShielding = 1;
				visual = "injury_hands";
				minimalHit = 0.01;
				depends = "HitArms";
			};
			class HitLegs: HitHands
			{
				armor = 3;
				material = -1;
				name = "legs";
				passThrough = 1;
				radius = 0.14;
				explosionShielding = 1;
				visual = "injury_legs";
				minimalHit = 0.01;
				depends = "0";
			};
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			}
		};
		armor = 2;
		armorStructural = 3;
		explosionShielding = 0.3;
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\40k_tau\Fire_Warrior\data\FW_Armour_CA",
			"\40k_tau\Pathfinder\data\Pathfinder_Cloth_CA"
		};
	};
	class ItemCore;
	class H_HelmetB: ItemCore
	{
		class ItemInfo;
	};
	class Binocular;
	class NVGoggles: Binocular
	{
		class ItemInfo;
	};
	class TIOW_IG_NVG: NVGoggles
	{
		author="Sokolonko";
		displayName="[Imperial]Imperial Guard NVG";
		modelOptics="\A3\weapons_f_exp\reticle\optics_night";
		model="\TIOW_IG_Cosmetics\IG_NVG\IG_NVG.p3d";
		picture="\TIOW_IG_Cosmetics\IG_NVG\data\nvg_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_NVG\data\IG_NVG_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			type=616;
			uniformModel="\TIOW_IG_Cosmetics\IG_NVG\IG_NVG.p3d";
			modelOff="\TIOW_IG_Cosmetics\IG_NVG\IG_NVG.p3d";
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TIOW_IG_Cosmetics\IG_NVG\data\IG_NVG_CA.paa"
			};
		};
	};
	class TIOW_IG_NVG_Green: TIOW_IG_NVG
	{
		author="Sokolonko";
		displayName="Imperial Guard NVG (Green)";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_NVG\data\IG_NVG_Green_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			type=616;
			uniformModel="\TIOW_IG_Cosmetics\IG_NVG\IG_NVG.p3d";
			modelOff="\TIOW_IG_Cosmetics\IG_NVG\IG_NVG.p3d";
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TIOW_IG_Cosmetics\IG_NVG\data\IG_NVG_Green_CA.paa"
			};
		};
	};
	class TIOW_Bionic_Eye: NVGoggles
	{
		author="Sokolonko";
		displayName="[Imperial]Bionic Eye (Advanced)";
		model="\TIOW_IG_Cosmetics\Bionic_Eye\IG_Bionic_Eye.p3d";
		picture="\TIOW_IG_Cosmetics\Bionic_Eye\data\bionic_eye_icon.paa";
		modelOptics="\TIOW_IG_Cosmetics\Bionic_Eye\Bionic_eye_reticle.p3d";
		visionMode[]=
		{
			"Normal",
			"NVG",
			"TI"
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Bionic_Eye\data\IG_Bionic_Eye_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			type=616;
			uniformModel="\TIOW_IG_Cosmetics\Bionic_Eye\IG_Bionic_Eye.p3d";
			modelOff="\TIOW_IG_Cosmetics\Bionic_Eye\IG_Bionic_Eye.p3d";
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TIOW_IG_Cosmetics\Bionic_Eye\data\IG_Bionic_Eye_CA.paa"
			};
		};
		identityTypes[]={};
	};
	class TIOW_Bionic_Eye_Green: TIOW_Bionic_Eye
	{
		author="Sokolonko";
		displayName="[Imperial]Bionic Eye (Basic)";
		visionMode[]=
		{
			"Normal",
			"NVG"
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Bionic_Eye\data\IG_Bionic_Eye_Green_CA.paa"
		};
		identityTypes[]={};
	};
	class TIOW_Bionic_Eye_2: NVGoggles
	{
		author="Sokolonko";
		displayName="[Imperial]Bionic Eye #2 (Advanced)";
		model="\TIOW_IG_Cosmetics\Bionic_Eye\IG_Bionic_Eye_2.p3d";
		picture="\TIOW_IG_Cosmetics\Bionic_Eye\data\bionic_eye_icon.paa";
		modelOptics="\TIOW_IG_Cosmetics\Bionic_Eye\Bionic_eye_reticle.p3d";
		visionMode[]=
		{
			"Normal",
			"NVG",
			"TI"
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Bionic_Eye\data\IG_Bionic_Eye_2_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			type=616;
			uniformModel="\TIOW_IG_Cosmetics\Bionic_Eye\IG_Bionic_Eye_2.p3d";
			modelOff="\TIOW_IG_Cosmetics\Bionic_Eye\IG_Bionic_Eye_2.p3d";
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TIOW_IG_Cosmetics\Bionic_Eye\data\IG_Bionic_Eye_2_CA.paa"
			};
		};
		identityTypes[]={};
	};
	class TIOW_Bionic_Eye_2_Green: TIOW_Bionic_Eye_2
	{
		author="Sokolonko";
		displayName="[Imperial]Bionic Eye #2 (Basic)";
		visionMode[]=
		{
			"Normal",
			"NVG"
		};
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Bionic_Eye\data\IG_Bionic_Eye_2_green_CA.paa"
		};
		identityTypes[]={};
	};
	class TIOW_IG_PatrolCap_836: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]836th Patrol Cap #1";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_1.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\836.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_1.p3d";
		};
	};
	class TIOW_IG_PatrolCap2_836: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]836th Patrol Cap #2";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_2.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\836.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_2.p3d";
		};
	};
	class TIOW_IG_PatrolCap3_836: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]836th Patrol Cap #3";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_3.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\836.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_3.p3d";
		};
	};
	class TIOW_IG_PatrolCap4_836: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]836th Patrol Cap #4";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_4.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\836.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_4.p3d";
		};
	};
	class TIOW_IG_PatrolCap_700: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]700th Patrol Cap #1";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_1.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\700.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_1.p3d";
		};
	};
	class TIOW_IG_PatrolCap2_700: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]700th Patrol Cap #2";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_2.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\700.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_2.p3d";
		};
	};
	class TIOW_IG_PatrolCap3_700: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]700th Patrol Cap #3";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_3.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\700.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_3.p3d";
		};
	};
	class TIOW_IG_PatrolCap4_700: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]700th Patrol Cap #4";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_4.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\700.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_4.p3d";
		};
	};
	class TIOW_IG_PatrolCap_776: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]776th Patrol Cap #1";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_1.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\776.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_1.p3d";
		};
	};
	class TIOW_IG_PatrolCap2_776: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]776th Patrol Cap #2";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_2.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\776.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_2.p3d";
		};
	};
	class TIOW_IG_PatrolCap3_776: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]776th Patrol Cap #3";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_3.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\776.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_3.p3d";
		};
	};
	class TIOW_IG_PatrolCap4_776: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]776th Patrol Cap #4";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_4.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\776.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_4.p3d";
		};
	};
	class TIOW_IG_PatrolCap_667: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]667th Patrol Cap #1";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_1.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\667.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_1.p3d";
		};
	};
	class TIOW_IG_PatrolCap2_667: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]667th Patrol Cap #2";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_2.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\667.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_2.p3d";
		};
	};
	class TIOW_IG_PatrolCap3_667: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]667th Patrol Cap #3";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_3.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\667.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_3.p3d";
		};
	};
	class TIOW_IG_PatrolCap4_667: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]667th Patrol Cap #4";
		picture="\TIOW_IG_Cosmetics\IG_Patrolcap\data\patrol_cap_icon.paa";
		model="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_4.p3d";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\IG_Patrolcap\data\667.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\IG_Patrolcap\IG_PatrolCap_4.p3d";
		};
	};
	class VestItem;
	class Cad_Gear_Vest2: ItemCore
	{
		class ItemInfo: VestItem
		{
		};
	};
	class TIOW_IG_Officer_Cap1_836: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #1 (836)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap1.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_836_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap1.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Officer_Cap2_836: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #2 (836)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap2.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_836_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap2.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Officer_Cap3_836: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #3 (836)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap3.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_836_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap3.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Sergeant_Armour_836: Cad_Gear_Vest2
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Cadian] Sergeant Flak Armor (836th)";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_SgtPlate_icon.paa";
		model="\TIOW_IG_Cosmetics\Captain\Sergeant_breastplate.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camoB",
			"RegimentCamo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\GM_FlakArmor_836_co.paa",
			"TIOW_IG_Cosmetics\Captain\data\Sergeant_breastplate_836_CA.paa",
			"CadFoot\Data\Textures\GM_FlakArmorReg_836_ca.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Sergeant_breastplate.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=78;
					passThrough=0.5;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=78;
					passThrough=0.5;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=78;
					passThrough=0.60000002;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=78;
					passThrough=0.60000002;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.30000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.60000002;
				};
			};
		};
	};
	class TIOW_IG_Officer_Armour_836: TIOW_IG_Sergeant_Armour_836
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Cadian] Officer Flak Armor (836th)";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerPads_icon.paa";
		model="\TIOW_IG_Cosmetics\Captain\Officer_shoulderpads.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"TIOW_IG_Cosmetics\Captain\data\Officer_shoulderpads_836_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Officer_shoulderpads.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
		};
	};
	class TIOW_IG_Golden_Armour: TIOW_IG_Sergeant_Armour_836
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Cadian] Officer Golden Shoulderpads";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerPads_icon.paa";
		model="\TIOW_IG_Cosmetics\Captain\Golden_shoulderpads.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"TIOW_IG_Cosmetics\Captain\data\Golden_shoulderpads_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Golden_shoulderpads.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
		};
	};
	class TIOW_IG_Officer_Cap1_776: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #1 (776)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap1.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_776_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap1.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Officer_Cap2_776: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #2 (776)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap2.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_776_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap2.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Officer_Cap3_776: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #3 (776)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap3.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_776_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap3.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Sergeant_Armour_776: Cad_Gear_Vest2
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Cadian] Sergeant Flak Armor (776th)";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_SgtPlate_icon.paa";
		model="\TIOW_IG_Cosmetics\Captain\Sergeant_breastplate.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camoB",
			"RegimentCamo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\GM_FlakArmor_776_co.paa",
			"TIOW_IG_Cosmetics\Captain\data\Sergeant_breastplate_776_CA.paa",
			"CadFoot\Data\Textures\GM_FlakArmorReg_776_ca.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Sergeant_breastplate.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=78;
					passThrough=0.5;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=78;
					passThrough=0.5;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=78;
					passThrough=0.60000002;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=78;
					passThrough=0.60000002;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.30000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.60000002;
				};
			};
		};
	};
	class TIOW_IG_Officer_Armour_776: TIOW_IG_Sergeant_Armour_776
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Cadian] Officer Flak Armor (776th)";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerPads_icon.paa";
		model="\TIOW_IG_Cosmetics\Captain\Officer_shoulderpads.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"TIOW_IG_Cosmetics\Captain\data\Officer_shoulderpads_776_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Officer_shoulderpads.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
		};
	};
	class TIOW_IG_Officer_Cap1_667: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #1 (667)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap1.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_667_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap1.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Officer_Cap2_667: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #2 (667)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap2.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_667_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap2.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Officer_Cap3_667: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #3 (667)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap3.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_667_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap3.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Sergeant_Armour_667: Cad_Gear_Vest2
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Cadian] Sergeant Flak Armor (667th)";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_SgtPlate_icon.paa";
		model="\TIOW_IG_Cosmetics\Captain\Sergeant_breastplate.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camoB",
			"RegimentCamo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\GM_FlakArmor_667_co.paa",
			"TIOW_IG_Cosmetics\Captain\data\Sergeant_breastplate_667_CA.paa",
			"CadFoot\Data\Textures\GM_FlakArmorReg_667_ca.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Sergeant_breastplate.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=78;
					passThrough=0.5;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=78;
					passThrough=0.5;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=78;
					passThrough=0.60000002;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=78;
					passThrough=0.60000002;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.30000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.60000002;
				};
			};
		};
	};
	class TIOW_IG_Officer_Armour_667: TIOW_IG_Sergeant_Armour_667
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Cadian] Officer Flak Armor (667th)";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerPads_icon.paa";
		model="\TIOW_IG_Cosmetics\Captain\Officer_shoulderpads.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"TIOW_IG_Cosmetics\Captain\data\Officer_shoulderpads_667_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Officer_shoulderpads.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
		};
	};
	class TIOW_IG_Officer_Cap1_700: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #1 (700)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap1.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_700_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap1.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Officer_Cap2_700: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #2 (700)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap2.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_700_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap2.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Officer_Cap3_700: H_HelmetB
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		author="Sokolonko";
		displayName="[Cadian]Officer Cap #3 (700)";
		model="\TIOW_IG_Cosmetics\Captain\Off_cap3.p3d";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerCap_icon.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TIOW_IG_Cosmetics\Captain\data\Officer_caps_700_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Off_cap3.p3d";
		};
		identityTypes[]={};
	};
	class TIOW_IG_Sergeant_Armour_700: Cad_Gear_Vest2
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Cadian] Sergeant Flak Armor (700th)";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_SgtPlate_icon.paa";
		model="\TIOW_IG_Cosmetics\Captain\Sergeant_breastplate.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camoB",
			"RegimentCamo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\GM_FlakArmor_700_co.paa",
			"TIOW_IG_Cosmetics\Captain\data\Sergeant_breastplate_700_CA.paa",
			"CadFoot\Data\Textures\GM_FlakArmorReg_700_ca.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Sergeant_breastplate.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=78;
					passThrough=0.5;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=78;
					passThrough=0.5;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=78;
					passThrough=0.60000002;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=78;
					passThrough=0.60000002;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.30000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.60000002;
				};
			};
		};
	};
	class TIOW_IG_Officer_Armour_700: TIOW_IG_Sergeant_Armour_700
	{
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayName="[Cadian] Officer Flak Armor (700th)";
		picture="\TIOW_IG_Cosmetics\Captain\data\IG_OfficerPads_icon.paa";
		model="\TIOW_IG_Cosmetics\Captain\Officer_shoulderpads.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"TIOW_IG_Cosmetics\Captain\data\Officer_shoulderpads_700_CA.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformModel="\TIOW_IG_Cosmetics\Captain\Officer_shoulderpads.p3d";
			containerClass="Supply80";
			overlaySelectionsInfo[]=
			{
				"ghillie_hide"
			};
		};
	};
};
