// Generated by unRap v1.06 by Kegetys
#include "script_macros_config.hpp"

class CfgVehicles {

    //////////////////////////////////////////////////////////////////////////////////////
	//TODO: Balance out the space marines so a Lucius pattern lasgun can't one shot them//
	//////////////////////////////////////////////////////////////////////////////////////

	
    class ThingX;	// External class reference
	class CAManBase;	// External class reference
	
	class SoldierWB : CAManBase {
		class HeadLimits;	// External class reference
	};
	
	class TIOWSpaceMarine_Base : SoldierWB {
		class HitPoints
		{
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			};
		};
	};

    
    class B_Soldier_F;
	class Strategic;
	class ReammoBox: Strategic
	{
	};
	class Bag_Base: ReammoBox
	{
	};
	class B_AssaultPack_Base: Bag_Base
	{
	};
	class B_AssaultPack_rgr: B_AssaultPack_Base
	{
	};
    
    class TIOW_CadBackpack: B_AssaultPack_Base
	{
		author="1st Legion";
		scope=2;
		picture="\CadFoot\Icon\Backpack_ca.paa";
		displayName="[Cadian] Infantry Backpack";
		model="\CadFoot\Model\Backpack.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\Backpack_co.paa"
		};
		class TransportMagazines
		{
			class _xx_M36KantRifle_mag
			{
				magazine="M36KantRifle_mag";
				count=6;
			};
			class _xx_HandGrenade
			{
				magazine="HandGrenade";
				count=4;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=2;
			};
		};
	};
    class TIOW_CadMedicaeBackpack: B_AssaultPack_Base
	{
		author="1st Legion";
		scope=2;
        maximumLoad = 240;
		picture="\CadFoot\Icon\Backpack_ca.paa";
		displayName="[Cadian] Medicae Backpack";
		model="\CadFoot\Model\Backpack.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\MedicaeBackpack_co.paa"
		};
		class TransportMagazines
		{
			class _xx_M36KantRifle_mag
			{
				magazine="M36KantRifle_mag";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=2;
			};
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
		};
	};

	class TIOW_CadMedicaeBackpack_Winter: B_AssaultPack_Base
	{
		author="1st Legion";
		scope=2;
        maximumLoad = 240;
		picture="\CadFoot\Icon\Backpack_ca.paa";
		displayName="[Cadian] Medicae Backpack (Winter Camo)";
		model="\CadFoot\Model\Backpack.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"CadFoot\Data\Textures\MedicaeBackpackWinter_co.paa"
		};
		class TransportMagazines
		{
			class _xx_M36KantRifle_mag
			{
				magazine="M36KantRifle_mag";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=2;
			};
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
		};
	};

    class VNG_CadATBackpack: TIOW_CadBackpack
	{
		displayName="[Cadian] Infantry AT Backpack";
	    maximumLoad = 320;
	};

    class B_Soldier_base_F;

    class DKoK_GM_1: B_Soldier_F
	{
		class HitPoints
		{
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			};
		};
		linkedItems[]=
		{
			"DKOKTroopMask",
			"DKoK_GM_Helm",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"TIOW_Krieg_Armor"
		};
		RespawnLinkedItems[]=
		{
			"DKOKTroopMask",
			"DKoK_GM_Helm",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"TIOW_Krieg_Armor"
		};
	};
    class TIOW_Comissar: B_Soldier_base_F
	{
		respawnLinkedItems[]=
		{
			"TIOW_Bionic_Eye",
			"TIOW_Comissar_Cap",
			"TIOW_Commissar_Armor"
		};
		class HitPoints
		{
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			};
		};
	};
    class TIOW_IG_Captain_667: B_Soldier_base_F
	{
		respawnLinkedItems[]=
		{
			"TIOW_Bionic_Eye",
			"TIOW_Comissar_Cap",
			"TIOW_Captain_Armor"
		};
		class HitPoints
		{
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			};
		};
	};
    class TIOW_Priest: B_Soldier_base_F
	{
		class HitPoints
		{
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			};
		};
	};
    class TIOW_Mordian_Trooper_1_Blu: B_Soldier_base_F
	{
		class HitPoints
		{
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			};
		};
	};
    class TIOW_Fire_Warrior: B_Soldier_base_F
	{
		class HitPoints
		{
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			};
		};
	};
	class TIOW_Valhallan_Trooper_1_Blu: B_Soldier_base_F
	{
		class HitPoints
		{
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			};
		};
	};
	class TIOW_Pathfinder: B_Soldier_base_F
	{
		class HitPoints
		{
			ADD_ACE_HITPOINTS(1,1);
			class ACE_HDBracket
			{
				armor = 1;
				material = -1;
				name = "head";
				passThrough = 0;
				radius = 1;
				explosionShielding = 1;
				visual = "";
				minimalHit = 0;
				depends = "HitHead";
			};
		};
	};
	
	class TIOW_Tau_Bck_Strike_VL;
    class VNG_Viorla_radioback: TIOW_Tau_Bck_Strike_VL
    {
        displayName = "Vior'la backpack radio";
        author = "firdon and dolf";
        mass = 50;
        maximumLoad = 260;
        tf_dialog = "rt1523g_radio_dialog";
        tf_dialogUpdate = "[""CH:1""] call TFAR_fnc_updateLRDialogToChannel;";
        tf_encryptionCode = "tf_west_radio_code";
        tf_hasLRradio = 1;
        tf_range = 40000;
        tf_subtype = "airborne";
    };
};
