// config.bin - 21:28:46 01/06/19, generated in 0.20 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#include "CfgPatches.hpp"
class UniformSlotInfo;	// External class reference
class B_Soldier_F;
class Strategic;    
#include "CfgVehicles.hpp"
class Mode_SemiAuto;	// External class reference
class Mode_Burst;	// External class reference
class Mode_FullAuto;	// External class reference
class SlotInfo;	// External class reference
class MuzzleSlot;	// External class reference
class CowsSlot;	// External class reference
class PointerSlot;	// External class reference
class UnderBarrelSlot;	// External class reference
#include "Cfgweapons.hpp"
class Default;
#include "CfgMagazines.hpp"
class Default;
class BulletBase;
#include "CfgAmmo.hpp"
class Default;
#include "CfgSmoke.hpp"